//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadFrontEnd.ServiceReferenceUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceUsuario.wsUsuarioSoap")]
    public interface wsUsuarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse Login(SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse> LoginAsync(SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarContra", ReplyAction="*")]
        SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse CambiarContra(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CambiarContra", ReplyAction="*")]
        System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse> CambiarContraAsync(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string Usuario, string Contrasena, string tipo) {
            this.Usuario = Usuario;
            this.Contrasena = Contrasena;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarContraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarContra", Namespace="http://tempuri.org/", Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequestBody Body;
        
        public CambiarContraRequest() {
        }
        
        public CambiarContraRequest(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarContraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nuevaContra;
        
        public CambiarContraRequestBody() {
        }
        
        public CambiarContraRequestBody(string Usuario, string Contrasena, string tipo, string nuevaContra) {
            this.Usuario = Usuario;
            this.Contrasena = Contrasena;
            this.tipo = tipo;
            this.nuevaContra = nuevaContra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CambiarContraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CambiarContraResponse", Namespace="http://tempuri.org/", Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponseBody Body;
        
        public CambiarContraResponse() {
        }
        
        public CambiarContraResponse(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CambiarContraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString CambiarContraResult;
        
        public CambiarContraResponseBody() {
        }
        
        public CambiarContraResponseBody(SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString CambiarContraResult) {
            this.CambiarContraResult = CambiarContraResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsUsuarioSoapChannel : SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsUsuarioSoapClient : System.ServiceModel.ClientBase<SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap>, SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap {
        
        public wsUsuarioSoapClient() {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsUsuarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap.Login(SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString Login(string Usuario, string Contrasena, string tipo) {
            SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest inValue = new SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest();
            inValue.Body = new SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            inValue.Body.tipo = tipo;
            SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse retVal = ((SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse> SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap.LoginAsync(SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.LoginResponse> LoginAsync(string Usuario, string Contrasena, string tipo) {
            SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest inValue = new SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequest();
            inValue.Body = new SeguridadFrontEnd.ServiceReferenceUsuario.LoginRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            inValue.Body.tipo = tipo;
            return ((SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap.CambiarContra(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest request) {
            return base.Channel.CambiarContra(request);
        }
        
        public SeguridadFrontEnd.ServiceReferenceUsuario.ArrayOfString CambiarContra(string Usuario, string Contrasena, string tipo, string nuevaContra) {
            SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest inValue = new SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest();
            inValue.Body = new SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            inValue.Body.tipo = tipo;
            inValue.Body.nuevaContra = nuevaContra;
            SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse retVal = ((SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap)(this)).CambiarContra(inValue);
            return retVal.Body.CambiarContraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse> SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap.CambiarContraAsync(SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest request) {
            return base.Channel.CambiarContraAsync(request);
        }
        
        public System.Threading.Tasks.Task<SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraResponse> CambiarContraAsync(string Usuario, string Contrasena, string tipo, string nuevaContra) {
            SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest inValue = new SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequest();
            inValue.Body = new SeguridadFrontEnd.ServiceReferenceUsuario.CambiarContraRequestBody();
            inValue.Body.Usuario = Usuario;
            inValue.Body.Contrasena = Contrasena;
            inValue.Body.tipo = tipo;
            inValue.Body.nuevaContra = nuevaContra;
            return ((SeguridadFrontEnd.ServiceReferenceUsuario.wsUsuarioSoap)(this)).CambiarContraAsync(inValue);
        }
    }
}
