//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeguridadFrontEnd.ServiceReferenceProducto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.wsProductoSoap")]
    public interface wsProductoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Buscar(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Buscar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> BuscarAsync(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Agregar(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Agregar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAsync(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Actualizar(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Actualizar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAsync(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] Eliminar(string codProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Eliminar", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAsync(string codProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsProductoSoapChannel : SeguridadFrontEnd.ServiceReferenceProducto.wsProductoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsProductoSoapClient : System.ServiceModel.ClientBase<SeguridadFrontEnd.ServiceReferenceProducto.wsProductoSoap>, SeguridadFrontEnd.ServiceReferenceProducto.wsProductoSoap {
        
        public wsProductoSoapClient() {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsProductoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public System.Data.DataTable Buscar(string texto, string criterio) {
            return base.Channel.Buscar(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> BuscarAsync(string texto, string criterio) {
            return base.Channel.BuscarAsync(texto, criterio);
        }
        
        public string[] Agregar(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria) {
            return base.Channel.Agregar(codProducto, nombre, unidadMedida, precio, stock, codCategoria);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAsync(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria) {
            return base.Channel.AgregarAsync(codProducto, nombre, unidadMedida, precio, stock, codCategoria);
        }
        
        public string[] Actualizar(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria) {
            return base.Channel.Actualizar(codProducto, nombre, unidadMedida, precio, stock, codCategoria);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAsync(string codProducto, string nombre, string unidadMedida, string precio, string stock, string codCategoria) {
            return base.Channel.ActualizarAsync(codProducto, nombre, unidadMedida, precio, stock, codCategoria);
        }
        
        public string[] Eliminar(string codProducto) {
            return base.Channel.Eliminar(codProducto);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAsync(string codProducto) {
            return base.Channel.EliminarAsync(codProducto);
        }
    }
}
